services:

    admin.page:
        class: Application\MainBundle\Admin\PageAdmin
        tags:
          - { name: sonata.admin, manager_type: orm, group: Zarządzanie stronami, label: Strony }
        arguments: [ ~, Application\MainBundle\Entity\Page, SonataAdminBundle:CRUD ]

    app.admin.collection:
        class: Application\MainBundle\Admin\CollectionAdmin
        tags:
            -
                group: collection.name_plural
                icon: '<i class="fa fa-star-o"></i>'
                label_catalogue: messages
                name: sonata.admin
                manager_type: orm
                label: collection.name_plural
        arguments:
            - ~
            - Application\MainBundle\Entity\Collection
            - ~

    app.admin.owner:
        class: Application\MainBundle\Admin\OwnerAdmin
        tags:
            -
                group: collection.name_plural
                icon: '<i class="fa fa-star-o"></i>'
                label_catalogue: messages
                name: sonata.admin
                manager_type: orm
                label: owner.name_plural
        arguments:
            - ~
            - Application\MainBundle\Entity\Owner
            - ~
            
    app.admin.collection.element:
        class: Application\MainBundle\Admin\CollectionElementAdmin
        tags:
            -
                group: collection.name_plural
                icon: '<i class="fa fa-star-o"></i>'
                label_catalogue: messages
                name: sonata.admin
                manager_type: orm
                label: collection.element.name_plural
        arguments:
            - ~
            - Application\MainBundle\Entity\CollectionElement
            - ~            