services:

    admin.page:
        class: Application\MainBundle\Admin\PageAdmin
        tags:
            - 
                name: sonata.admin
                manager_type: orm
                icon: '<i class="fa fa-edit"></i>'
                label_catalogue: messages
                group: Page management
                label: Pages
        arguments:
            - ~
            - Application\MainBundle\Entity\Page
            - 'PixSortableBehaviorBundle:SortableAdmin'
        calls:
             - [ setPositionService, [@pix_sortable_behavior.position]]
         
    admin.page.group:
        class: Application\MainBundle\Admin\PageCategoryAdmin
        tags:
            - 
                name: sonata.admin
                manager_type: orm
                icon: '<i class="fa fa-edit"></i>'
                label_catalogue: messages
                group: Page management
                label: Categories
        arguments:
            - ~
            - Application\MainBundle\Entity\PageCategory
            - 'PixSortableBehaviorBundle:SortableAdmin'
        calls:
             - [ setPositionService, [@pix_sortable_behavior.position]]

# ------------------------------------------------------------------------------

    app.admin.collection:
        class: Application\MainBundle\Admin\CollectionAdmin
        tags:
            -
                group: collection.name_plural
                icon: '<i class="fa fa-star-o"></i>'
                label_catalogue: messages
                name: sonata.admin
                manager_type: orm
                label: collection.name_plural
        arguments:
            - ~
            - Application\MainBundle\Entity\Collection
            - ~

    app.admin.owner:
        class: Application\MainBundle\Admin\OwnerAdmin
        tags:
            -
                group: collection.name_plural
                icon: '<i class="fa fa-star-o"></i>'
                label_catalogue: messages
                name: sonata.admin
                manager_type: orm
                label: owner.name_plural
        arguments:
            - ~
            - Application\MainBundle\Entity\Owner
            - ~
            
    app.admin.collection.element:
        class: Application\MainBundle\Admin\CollectionElementAdmin
        tags:
            -
                group: collection.name_plural
                icon: '<i class="fa fa-star-o"></i>'
                label_catalogue: messages
                name: sonata.admin
                manager_type: orm
                label: collection.element.name_plural
        arguments:
            - ~
            - Application\MainBundle\Entity\CollectionElement
            - ~            