services:

    admin.page:
        class: Application\MainBundle\Admin\PageAdmin
        tags:
            -
                name: sonata.admin
                manager_type: orm
                icon: '<i class="fa fa-edit"></i>'
                label_catalogue: messages
                group: Page management
                label: Pages
        arguments:
            - ~
            - Application\MainBundle\Entity\Page
            - 'PixSortableBehaviorBundle:SortableAdmin'
        calls:
             - [ setPositionService, ["@pix_sortable_behavior.position"]]

    admin.page.group:
        class: Application\MainBundle\Admin\PageCategoryAdmin
        tags:
            -
                name: sonata.admin
                manager_type: orm
                icon: '<i class="fa fa-edit"></i>'
                label_catalogue: messages
                group: Page management
                label: Categories
        arguments:
            - ~
            - Application\MainBundle\Entity\PageCategory
            - 'PixSortableBehaviorBundle:SortableAdmin'
        calls:
             - [ setPositionService, ["@pix_sortable_behavior.position"]]
