sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account: # used to display menu option (login option)

        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]