sonata_user:
    security_acl: true
    manager_type: orm # can be orm or mongodb
    impersonating:
        route:      default.home
        parameters: { }
    profile:
        form:
            type: app_user_profile
        register:
            form:
                type: app_user_registration
