application_main:
    settings: ~
    user_settings:
        -
            category: "general"
            name: "identification"
            type: "enum"
            data: {"username":"username","id":"id","nickname":"nickname","firstName":"firstName","lastName":"lastName","fullName":"fullName"}
            default: "username"            
    main_menu:
        -
            label: Home
            route: default.home
            routeParameters: {}
            icon: home
        -
            label: Contact
            route: default.contact
            icon: envelope
        -
            label: Private
            icon: lock
            role: ROLE_USER
            children: 
                -
                    label: Settings
                    route: fos_user_profile_show
                    icon: cog
                    role: ROLE_USER
                -
                    label: Private
                    route: private.index
                    icon: lock
                    role: ROLE_USER
                -
                    label: Gallery
                    route: private.gallery
                    icon: camera-retro
                    role: ROLE_USER
                -
                    label: Admin
                    route: sonata_admin_dashboard
                    icon: wrench
                    role: ROLE_ADMIN 

        -
            label: ~
            icon: globe
            children:
                -
                    label: Polski
                    route: locale.switch
                    routeParameters: { locale: pl }
                -
                    label: English
                    route: locale.switch
                    routeParameters: { locale: en }
