#doctrine:
#    dbal:
#        default_connection:   default
#        types:
#            # A collection of custom types
#            # Example
#            some_custom_type:
#                class:                Acme\HelloBundle\MyCustomType
#                commented:            true
#        # If enabled all tables not prefixed with sf2_ will be ignored by the schema
#        # tool. This is for custom tables which should not be altered automatically.
#        #schema_filter:        ^sf2_
#
#        connections:
#            # A collection of different named connections (e.g. default, conn2, etc)
#            default:
#                dbname:               ~
#                host:                 localhost
#                port:                 ~
#                user:                 root
#                password:             ~
#                charset:              ~
#                path:                 ~
#                memory:               ~
#
#                # The unix socket to use for MySQL
#                unix_socket:          ~
#
#                # True to use as persistent connection for the ibm_db2 driver
#                persistent:           ~
#
#                # The protocol to use for the ibm_db2 driver (default to TCPIP if omitted)
#                protocol:             ~
#
#                # True to use dbname as service name instead of SID for Oracle
#                service:              ~
#
#                # The session mode to use for the oci8 driver
#                sessionMode:          ~
#
#                # True to use a pooled server with the oci8 driver
#                pooled:               ~
#
#                # Configuring MultipleActiveResultSets for the pdo_sqlsrv driver
#                MultipleActiveResultSets:  ~
#                driver:               pdo_mysql
#                platform_service:     ~
#
#                # the version of your database engine
#                server_version:       ~
#
#                # when true, queries are logged to a "doctrine" monolog channel
#                logging:              "%kernel.debug%"
#                profiling:            "%kernel.debug%"
#                driver_class:         ~
#                wrapper_class:        ~
#                options:
#                    # an array of options
#                    key:                  []
#                mapping_types:
#                    # an array of mapping types
#                    name:                 []
#                slaves:
#
#                    # a collection of named slave connections (e.g. slave1, slave2)
#                    slave1:
#                        dbname:               ~
#                        host:                 localhost
#                        port:                 ~
#                        user:                 root
#                        password:             ~
#                        charset:              ~
#                        path:                 ~
#                        memory:               ~
#
#                        # The unix socket to use for MySQL
#                        unix_socket:          ~
#
#                        # True to use as persistent connection for the ibm_db2 driver
#                        persistent:           ~
#
#                        # The protocol to use for the ibm_db2 driver (default to TCPIP if omitted)
#                        protocol:             ~
#
#                        # True to use dbname as service name instead of SID for Oracle
#                        service:              ~
#
#                        # The session mode to use for the oci8 driver
#                        sessionMode:          ~
#
#                        # True to use a pooled server with the oci8 driver
#                        pooled:               ~
#
#                        # the version of your database engine
#                        server_version:       ~
#
#                        # Configuring MultipleActiveResultSets for the pdo_sqlsrv driver
#                        MultipleActiveResultSets:  ~
#
#    orm:
#        default_entity_manager:  ~
#        auto_generate_proxy_classes:  false
#        proxy_dir:            "%kernel.cache_dir%/doctrine/orm/Proxies"
#        proxy_namespace:      Proxies
#        # search for the "ResolveTargetEntityListener" class for a cookbook about this
#        resolve_target_entities: []
#        entity_managers:
#            # A collection of different named entity managers (e.g. some_em, another_em)
#            some_em:
#                query_cache_driver:
#                    type:                 array # Required
#                    host:                 ~
#                    port:                 ~
#                    instance_class:       ~
#                    class:                ~
#                metadata_cache_driver:
#                    type:                 array # Required
#                    host:                 ~
#                    port:                 ~
#                    instance_class:       ~
#                    class:                ~
#                result_cache_driver:
#                    type:                 array # Required
#                    host:                 ~
#                    port:                 ~
#                    instance_class:       ~
#                    class:                ~
#                connection:           ~
#                class_metadata_factory_name:  Doctrine\ORM\Mapping\ClassMetadataFactory
#                default_repository_class:  Doctrine\ORM\EntityRepository
#                auto_mapping:         false
#                hydrators:
#
#                    # An array of hydrator names
#                    hydrator_name:                 []
#                mappings:
#                    # An array of mappings, which may be a bundle name or something else
#                    mapping_name:
#                        mapping:              true
#                        type:                 ~
#                        dir:                  ~
#                        alias:                ~
#                        prefix:               ~
#                        is_bundle:            ~
#                dql:
#                    # a collection of string functions
#                    string_functions:
#                        # example
#                        # test_string: Acme\HelloBundle\DQL\StringFunction
#
#                    # a collection of numeric functions
#                    numeric_functions:
#                        # example
#                        # test_numeric: Acme\HelloBundle\DQL\NumericFunction
#
#                    # a collection of datetime functions
#                    datetime_functions:
#                        # example
#                        # test_datetime: Acme\HelloBundle\DQL\DatetimeFunction
#
#                # Register SQL Filters in the entity manager
#                filters:
#                    # An array of filters
#                    some_filter:
#                        class:                ~ # Required
#                        enabled:              false