doctrine:
    dbal:
        types:
            json: Sonata\Doctrine\Types\JsonType
            collection_type: Application\MainBundle\Doctrine\DBAL\Types\CollectionTypeType
            collection_element_type: Application\MainBundle\Doctrine\DBAL\Types\CollectionElementTypeType
    orm:
        entity_managers:
            default:
                mappings:
                    FOSUserBundle: ~
                    ApplicationSonataUserBundle: ~
                    SonataUserBundle: ~