application_main:
    resource: "@ApplicationMainBundle/Controller/"
    type:     annotation
    prefix:   /

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin