application_main:
    resource: "@ApplicationMainBundle/Controller/"
    type:     annotation
    prefix:   /

siciarek_chat_bundle:
    resource: "@SiciarekChatBundle/Controller"
    type: annotation
    prefix: /chat

# -------------------------------------------------------------------

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

# -------------------------------------------------------------------

sonata_user_security:
     resource: "@SonataUserBundle/Resources/config/routing/sonata_security_2.xml"

sonata_user_resetting:
     resource: "@SonataUserBundle/Resources/config/routing/sonata_resetting_2.xml"
     prefix: /resetting

sonata_user_profile:
     resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_2.xml"
     prefix: /profile

sonata_user_register:
     resource: "@SonataUserBundle/Resources/config/routing/sonata_registration_2.xml"
     prefix: /register

sonata_user_change_password:
     resource: "@SonataUserBundle/Resources/config/routing/sonata_change_password_2.xml"
     prefix: /profile

sonata_user_admin_resetting:
     resource: "@SonataUserBundle/Resources/config/routing/admin_resetting.xml"
     prefix: /resetting

# -------------------------------------------------------------------

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

# -------------------------------------------------------------------

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

# -------------------------------------------------------------------

#gallery:
#    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
#    prefix: /media/gallery
#
#media:
#    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
#    prefix: /media

# -------------------------------------------------------------------
