twig:
    globals:
        app_name: %app_name%
        app_description: %app_description%
        bootstrapVersion: '3.3.6'
        jqueryVersion: '2.2.0'
        fontAwesomeVersion: '4.5.0'
        defaultFormTheme:
            - 'bootstrap_3_horizontal_layout.html.twig'
            - '::form_fields.html.twig'
    form_themes: []
    number_format:
        decimals: 2
        decimal_point: ','
        thousands_separator: ' '
    date:
        format: Y-m-d H:i
        timezone: %default_timezone%
