ivory_ck_editor:

    plugins:
        youtube:
            path:     "/bundles/applicationmain/js/ckeditor/plugins/youtube/"
            filename: "plugin.js"

    toolbars:
        items:
            basic_typography: ['Bold', 'Italic', 'Underline']
            basic_links: ['Link', 'Unlink']
            color: ['TextColor', 'BGColor']
            show: ['Maximize', 'ShowBlocks']
            save: ['Save']
            typography: ['Bold', 'Italic', 'Underline', 'Strike', '-', 'Subscript', 'Superscript']
            edit: ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'SpellChecker', 'Scayt']
            elements: ['Link', 'Image', 'Youtube', 'Flash', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar']
            alignment: ['JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiRtl', 'BidiLtr']
            find: ['Undo', 'Redo', 'Find', 'Replace', '-', 'SelectAll', 'RemoveFormat']
            format: ['Format', 'Source']
            lists: ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', 'Blockquote']
            links: ['Link', 'Unlink', 'Anchor', 'LinkToNode', 'LinkToMenu']
        configs:
            basic:
                - "@basic_typography"
                - "@basic_links"
                - "@color"
                - "@show"
            extended:
                - "@save"
                - "@show"
                - "@typography"
                - "@links"
                - "@color"
                - "@edit"
                - "@elements"
                - "@alignment"
                - "@find"
                - "@format"
                - "@lists"


    configs:
        basic:
            htmlEncodeOutput: false
            entities: false
            width: 100%
            height: 200
            toolbar: basic
        email:
            htmlEncodeOutput: false
            entities: false
            width: 100%
            height: 150
            toolbar: basic
            removePlugins: 'elementspath'
        extended:
            htmlEncodeOutput: false
            entities: false
            width: 100%
            height: 300
            contentsCss: '/bundles/applicationmain/css/ckeditor.css'
            toolbar: extended
            filebrowserBrowseUrl : '/bundles/applicationmain/js/pdw_file_browser/index.php'
            filebrowserImageBrowseUrl : '/bundles/applicationmain/js/pdw_file_browser/index.php?filter=image'
            filebrowserFlashBrowseUrl : '/bundles/applicationmain/js/pdw_file_browser/index.php?filter=flash'
            extraPlugins: youtube

