ivory_ck_editor:

#    plugins:
#        youtube:
#            path:     "/bundles/applicationmain/js/ckeditor/plugins/youtube/"
#            filename: "plugin.js"
#        colorbutton:
#            path:     "/bundles/applicationmain/js/ckeditor/plugins/colorbutton/"
#            filename: "plugin.js"
    toolbars:
        items:
            basic_typography: ['Bold', 'Italic', 'Underline']
            basic_links: ['Link', 'Unlink']
            color: ['TextColor', 'BGColor']
            save: ['Save', 'Maximize', 'ShowBlocks']
            typography: ['Bold', 'Italic', 'Underline', 'Strike', '-', 'Subscript', 'Superscript']
            edit: ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'SpellChecker', 'Scayt']
            elements: ['Image', 'Flash', 'Youtube', 'Link', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar']
            alignment: ['JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiRtl', 'BidiLtr']
            find: ['Undo', 'Redo', 'Find', 'Replace', '-', 'SelectAll', 'RemoveFormat']
            format: ['Format', 'Source']
            lists: ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', 'Blockquote']
            links: ['Link', 'Unlink', 'Anchor', 'LinkToNode', 'LinkToMenu']
        configs:
            basic:
                - @basic_typography
                - @basic_links
                - @color
            extended:
                - @save
                - @typography
                - @color
                - @edit
                - @elements
                - @alignment
                - @find
                - @format
                - @lists
                - @links

    configs:
        email:
            width: 100%
            height: 150
            toolbar: basic
#            contentsCss: '/bundles/applicationmain/css/ckeditor.css'
            removePlugins: 'elementspath'
        basic:
            width: 100%
            height: 150
            toolbar: basic
#            contentsCss: '/bundles/applicationmain/css/ckeditor.css'
            removePlugins: 'elementspath'

#        basic_tall:
#            width: 100%
#            height: 350
#            toolbar: basic
#            contentsCss: '/bundles/applicationmain/css/ckeditor.css'
#            removePlugins: 'elementspath'
#
#        extended:
#            width: 90%
#            height: 300
#            contentsCss: '/bundles/applicationmain/css/ckeditor.css'
#            toolbar: extended
#            filebrowserBrowseUrl : '/bundles/applicationmain/js/pdw_file_browser/index.php'
#            filebrowserImageBrowseUrl : '/bundles/applicationmain/js/pdw_file_browser/index.php?filter=image'
#            filebrowserFlashBrowseUrl : '/bundles/applicationmain/js/pdw_file_browser/index.php?filter=flash'
#            removePlugins: 'elementspath'
