services:

    app.locale_listener:
        class: Application\MainBundle\EventListener\LocaleListener
        arguments: [ "%kernel.default_locale%" ]
        tags:
            - { name: kernel.event_subscriber }
            
    app.twig.extension:
        class: Application\MainBundle\Twig\Extension\TwigExtension
        arguments: [ @twig.loader, @router, @ewz_text.text_helper, @service_container ]
        tags:
            -
                name:   twig.extension
            