services:
    app.pages:
        class: Application\MainBundle\Common\Page
        arguments: [ '@service_container' ]

    pages:
        alias: app.pages
   
    app.form.registration:
        class: Application\MainBundle\Common\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
    request:
        class: Symfony\Component\HttpFoundation\Request

    app.entity.parameter:
        class: Application\MainBundle\Common\Parameter
        arguments: [ '@doctrine.orm.entity_manager' ]
    
    eparam:
        alias: app.entity.parameter
     
    app.form.email.message:
        class: Application\MainBundle\Common\Form\EmailMessageType
        arguments: [ ]
        tags:
            - { name: form.type, alias: email_message }
            
    app.image.converter:
        class: Application\MainBundle\Service\ImageConverter
        arguments: [ '@service_container' ]

    app.common.utils.curl:
        class: Application\MainBundle\Common\Utils\Curl

    app.common.utils.curl.debug:
        class: Application\MainBundle\Common\Utils\Curl

    app.common.email.sender:
        class: Application\MainBundle\Common\EmailSender
        arguments: [ '@mailer' ]
        calls:
            - [ setContainer, [ '@service_container' ] ]

    app.common.laaf.frame:
        class: Application\MainBundle\Common\LaafFrame

    laaf:
        alias: app.common.laaf.frame
        
    app.locale_listener:
        class: Application\MainBundle\EventListener\LocaleListener
        arguments: [ "%kernel.default_locale%" ]
        tags:
            - { name: kernel.event_subscriber }
            
    app.twig.extension:
        class: Application\MainBundle\Twig\Extension\TwigExtension
        arguments: [ '@twig.loader', '@router', '@ewz_text.text_helper', '@service_container' ]
        tags:
            -
                name:   twig.extension
