services:

    app.locale_listener:
        class: Application\MainBundle\EventListener\LocaleListener
        arguments: [ "%kernel.default_locale%" ]
        tags:
            - { name: kernel.event_subscriber }