services:
    app.image.converter:
        class: Application\MainBundle\Service\ImageConverter
        arguments:
            - @service_container

    app.common.utils.curl:
        class: Application\MainBundle\Common\Utils\Curl

    app.common.utils.curl.debug:
        class: Application\MainBundle\Common\Utils\Curl

    app.common.email.sender:
        class: Application\MainBundle\Common\EmailSender
        arguments: [ @mailer ]

    app.common.laaf.frame:
        class: Application\MainBundle\Common\LaafFrame

    app.locale_listener:
        class: Application\MainBundle\EventListener\LocaleListener
        arguments: [ "%kernel.default_locale%" ]
        tags:
            - { name: kernel.event_subscriber }
            
    app.twig.extension:
        class: Application\MainBundle\Twig\Extension\TwigExtension
        arguments: [ @twig.loader, @router, @ewz_text.text_helper, @service_container ]
        tags:
            -
                name:   twig.extension
