hwi_oauth:
    firewall_name: secure_area
    resource_owners:
        facebook:
            type:                facebook
            client_id:           %oauth_facebook_client_id%
            client_secret:       %oauth_facebook_client_secret%
            scope:               "email"
