parameters:
    knp_menu.renderer.twig.options:
        currentClass: active

knp_menu:
    twig:
        template: knp_menu.html.twig
    templating: false
    default_renderer: twig

services:
    app.menu_builder:
        class: Application\MainBundle\Menu\Builder
        arguments:
            - @knp_menu.factory
            - @translator
            - @security.authorization_checker
        tags:
            -
                name: knp_menu.menu_builder
                method: getMainMenu
                alias: main
