knp_menu:
    # use "twig: false" to disable the Twig extension and the TwigRenderer
    twig:
        template: knp_menu.html.twig
    #  if true, enables the helper for PHP templates
    templating: false
    # the renderer to use, list is also available by default
    default_renderer: twig

services:
    app.menu_builder:
        class: Application\MainBundle\Menu\Builder
        arguments:
            - @knp_menu.factory
            - @translator
            - @security.context
        tags:
            -
                name: knp_menu.menu_builder
                method: getMainMenu
                alias: main
