ekino_wordpress:
    globals:                         # If you have some custom global variables that WordPress needs
        - wp_global_var
    table_prefix: "wp_"              # If you have a specific Wordpress table prefix
    wordpress_directory: "%kernel.root_dir%/../web/wordpress" # If you have a specific Wordpress directory structure
    load_twig_extension: true        # If you want to enable native WordPress functions (ie : get_option() => wp_get_option())
    enable_wordpress_listener: false # If you want to disable the WordPress request listener
    security:
        firewall_name: "main"        # This is the firewall default name
        login_url: "/wp-login.php"   # Absolute URL to the wordpress login page
