a2lix_translation_form:
    locale_provider: default
    locales: [pl, en]
    default_locale: pl
    required_locales: [pl]
    manager_registry: doctrine
    templating: 'A2lixTranslationFormBundle::default.html.twig'