<?php

namespace Application\MainBundle\Entity;

use Knp\DoctrineBehaviors\ORM as ORMBehaviors;

/**
 * AdministrativeDivisionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdministrativeDivisionRepository extends \Doctrine\ORM\EntityRepository
{
    use ORMBehaviors\Tree\Tree;
    
}
