<?php

namespace Application\MainBundle\Entity;

/**
 * CollectionElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollectionElementRepository extends \Doctrine\ORM\EntityRepository
{
}
