fos_user:
    db_driver:      orm # can be orm or odm
    firewall_name:  main
    user_class:     Application\Sonata\UserBundle\Entity\User

    group:
        group_class:   Application\Sonata\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager                    # If you're using doctrine orm (use sonata.user.mongodb.user_manager for mongodb)

    service:
        user_manager: sonata.user.orm.user_manager                      # If you're using doctrine orm (use sonata.user.mongodb.group_manager for mongodb)
        mailer: fos_user.mailer.twig_swift

    from_email:
        address: %mailer_default_email%
        sender_name: %app_name%

    resetting:
        email:
            template: email/password_resetting.email.twig

    registration:
        confirmation:
            enabled: true
            template: email/registration.email.twig
